### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by t-young31** [duartegroup/cgbind#11]
- update setup.py
- pypi release
- fix pip build:

```
$ pip install cgbind
Collecting cgbind
  Downloading cgbind-1.0.3.tar.gz (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.9/293.9 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6g/ksrw0l0n3456zw_lmkp08t1c0000gn/T/pip-install-8g915m1e/cgbind_6bf36b11dc474eda891b4a3360c21a65/setup.py", line 2, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
```

**Comment by t-young31** [comment]
upload to test pypi

```
python3 -m build
python3 -m pip install --upgrade twine
python3 -m twine upload --repository testpypi dist/*
```

test distro with:

```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple cgbind==1.0.4
```

**Comment by t-young31** [comment]
real upload 

```
python -m twine upload dist/*
```
